//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp6
{
    using System;
    using System.Collections.Generic;
    
    public partial class Degree
    {
        public int Eid { get; set; }
        public int Id { get; set; }
        public string ExamName { get; set; }
        public Nullable<int> Degree1 { get; set; }
    
        public virtual school school { get; set; }
    }
}
